# Generated by Django 3.0.7 on 2021-04-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210421_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='costumer_need',
            new_name='customer_need',
        ),
    ]
