# Generated by Django 3.1.7 on 2021-04-08 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20210408_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='google_plus_link',
            new_name='linkedin_link',
        ),
    ]
