# Generated by Django 3.0.7 on 2021-04-30 15:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20210430_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='added_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
