# Generated by Django 3.0.7 on 2021-05-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_post_added_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='location',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
