# Generated by Django 3.0.7 on 2021-05-01 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
