# Generated by Django 3.0.7 on 2021-05-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_remove_post_place_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='place_photo',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
