# Generated by Django 3.0.7 on 2021-05-04 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20210504_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='place_photo',
            field=models.ImageField(default='bg-img-6.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
