# Generated by Django 3.0.7 on 2021-05-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_auto_20210504_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='place_photo',
            field=models.ImageField(default='default.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
