# Generated by Django 3.0.7 on 2021-05-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_auto_20210504_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='place_photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
