# Generated by Django 3.0.7 on 2021-05-17 10:12

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0011_auto_20210509_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='full_desc',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
    ]
