# Generated by Django 3.0.7 on 2021-05-18 09:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0012_auto_20210517_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='full_desc',
            field=ckeditor.fields.RichTextField(default=' ', max_length=10485760),
        ),
    ]
