# Generated by Django 3.0.7 on 2021-05-18 11:02

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_auto_20210518_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='full_desc',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=' '),
        ),
    ]
