# Generated by Django 3.0.7 on 2021-05-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0014_auto_20210518_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='short_desc',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
