# Generated by Django 3.0.7 on 2021-05-14 15:33

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_title', models.CharField(max_length=255)),
                ('country', models.CharField(default=' ', max_length=100)),
                ('location', models.CharField(default=' ', max_length=100)),
                ('description', ckeditor.fields.RichTextField()),
                ('place_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('place_photo_1', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('place_photo_2', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('place_photo_3', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('place_photo_4', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('is_recommended', models.BooleanField(default=False)),
                ('one_strong_point_for_recommendations', models.CharField(blank='True', default='In 2-3 words', max_length=100)),
                ('architecture', models.CharField(max_length=100)),
                ('feature1', models.CharField(default=' ', max_length=100)),
                ('feature2', models.CharField(default=' ', max_length=100)),
                ('feature3', models.CharField(default=' ', max_length=100)),
                ('feature4', models.CharField(default=' ', max_length=100)),
                ('Explain_each_feature', ckeditor.fields.RichTextField(default=' ')),
                ('Reasons_to_visit', ckeditor.fields.RichTextField(default=' ')),
                ('story1', ckeditor.fields.RichTextField(default=' ')),
                ('story2', ckeditor.fields.RichTextField(default=' ')),
                ('story3', ckeditor.fields.RichTextField(default=' ')),
                ('story4', ckeditor.fields.RichTextField(default=' ')),
                ('Max_temperature', models.CharField(default='', max_length=100)),
                ('Min_temperature', models.CharField(default='', max_length=100)),
                ('sea_level', models.CharField(default='', max_length=10000)),
                ('no_of_visitors', models.CharField(default='Around x million', max_length=1000000)),
                ('closeness_of_the_destination', ckeditor.fields.RichTextField()),
                ('added_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
