# Generated by Django 3.1.7 on 2021-04-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_title', models.CharField(max_length=255)),
                ('country', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District Of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')], max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('place_photo', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('place_photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('place_photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('place_photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('place_photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('city', models.CharField(max_length=100)),
                ('is_featured', models.BooleanField(max_length=100)),
                ('architecture', models.CharField(max_length=100)),
                ('populariry', models.CharField(max_length=100)),
                ('closeness_of_the_destination', models.TextField(max_length=1000)),
            ],
        ),
    ]
