# Generated by Django 3.1.7 on 2021-04-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
