# Generated by Django 3.0.7 on 2021-04-13 11:09

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_auto_20210413_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='populariry',
        ),
        migrations.AddField(
            model_name='place',
            name='sea_level',
            field=models.IntegerField(default=12, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='place',
            name='closeness_of_the_destination',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='place',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
