# Generated by Django 3.0.7 on 2021-05-14 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_place_post_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='post_views',
            new_name='place_views',
        ),
    ]
