# Generated by Django 3.0.7 on 2021-04-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_auto_20210413_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='sea_level',
            field=models.IntegerField(max_length=10000),
        ),
    ]
