# Generated by Django 3.0.7 on 2021-05-18 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_auto_20210514_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place_views',
            field=models.IntegerField(default=0),
        ),
    ]
