# Generated by Django 3.0.7 on 2021-05-28 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0004_auto_20210518_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='field_name',
            field=models.URLField(default='add photo url', max_length=500),
        ),
    ]
