# Generated by Django 3.0.7 on 2021-06-03 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_place_field_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='field_name',
        ),
    ]
