# Generated by Django 3.0.7 on 2021-04-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0005_auto_20210413_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='is_featured',
            new_name='is_trending',
        ),
    ]
