# Generated by Django 3.0.7 on 2021-04-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0006_auto_20210413_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
