# Generated by Django 3.0.7 on 2021-04-13 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0007_place_is_recommended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='city',
        ),
        migrations.AddField(
            model_name='place',
            name='added_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='place',
            name='location',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='speciality',
            field=models.CharField(default='SOME STRING', max_length=100),
        ),
    ]
