# Generated by Django 3.0.7 on 2021-04-15 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0008_auto_20210413_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='speciality',
        ),
        migrations.AddField(
            model_name='place',
            name='feature1',
            field=models.CharField(default='like: extensive use of marble', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='feature2',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='feature3',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='feature4',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='feature5',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='no_of_visitors',
            field=models.CharField(default='1000', max_length=1000000),
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.CharField(default='Agra', max_length=100),
        ),
    ]
