# Generated by Django 3.0.7 on 2021-04-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0010_auto_20210415_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='feature2',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='feature3',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='feature4',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='feature5',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
    ]
