# Generated by Django 3.0.7 on 2021-04-15 15:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0011_auto_20210415_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='story1',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
        migrations.AddField(
            model_name='place',
            name='story2',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
        migrations.AddField(
            model_name='place',
            name='story3',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
        migrations.AddField(
            model_name='place',
            name='story4',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
    ]
