# Generated by Django 3.0.7 on 2021-04-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0013_place_one_strong_point_for_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='temperature',
            field=models.CharField(default='in ℃', max_length=100),
        ),
    ]
