# Generated by Django 3.0.7 on 2021-04-16 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0014_place_temperature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='temperature',
            new_name='Avg_annual_temperature',
        ),
    ]
