# Generated by Django 3.0.7 on 2021-04-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0015_auto_20210416_2003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='Avg_annual_temperature',
            new_name='Max_temperature',
        ),
        migrations.AddField(
            model_name='place',
            name='Min_temperature',
            field=models.CharField(default='in ℃', max_length=100),
        ),
    ]
