# Generated by Django 3.0.7 on 2021-04-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0016_auto_20210416_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='Reason2',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='Reason3',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='Reason4',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='Reason5',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='Reason_to_visit',
            field=models.CharField(blank=True, default='like sake brewing', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='weather_APR_JUL',
            field=models.CharField(default='like: Mostly freezing', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='weather_AUG_NOV',
            field=models.CharField(default='like: Mostly freezing', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='weather_DEC_MAR',
            field=models.CharField(default='like: Mostly freezing', max_length=100),
        ),
    ]
