# Generated by Django 3.0.7 on 2021-04-17 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0020_auto_20210417_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='feature1',
            field=models.CharField(default='like: extensive use of marble', max_length=500),
        ),
        migrations.AlterField(
            model_name='place',
            name='feature2',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='place',
            name='feature3',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='place',
            name='feature4',
            field=models.CharField(default=' ', max_length=500),
        ),
        migrations.AlterField(
            model_name='place',
            name='feature5',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
