# Generated by Django 3.0.7 on 2021-04-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0022_auto_20210417_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='Reason2',
            field=models.CharField(default=' ', max_length=10000),
        ),
        migrations.AlterField(
            model_name='place',
            name='Reason3',
            field=models.CharField(default=' ', max_length=10000),
        ),
        migrations.AlterField(
            model_name='place',
            name='Reason4',
            field=models.CharField(default=' ', max_length=10000),
        ),
        migrations.AlterField(
            model_name='place',
            name='Reason5',
            field=models.CharField(default=' ', max_length=10000),
        ),
        migrations.AlterField(
            model_name='place',
            name='Reason_to_visit',
            field=models.CharField(default='like sake brewing', max_length=10000),
        ),
    ]
