# Generated by Django 3.0.7 on 2021-04-17 09:20

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0023_auto_20210417_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='Reason2',
        ),
        migrations.RemoveField(
            model_name='place',
            name='Reason3',
        ),
        migrations.RemoveField(
            model_name='place',
            name='Reason4',
        ),
        migrations.RemoveField(
            model_name='place',
            name='Reason5',
        ),
        migrations.RemoveField(
            model_name='place',
            name='Reason_to_visit',
        ),
        migrations.RemoveField(
            model_name='place',
            name='feature1',
        ),
        migrations.RemoveField(
            model_name='place',
            name='feature2',
        ),
        migrations.RemoveField(
            model_name='place',
            name='feature3',
        ),
        migrations.RemoveField(
            model_name='place',
            name='feature4',
        ),
        migrations.RemoveField(
            model_name='place',
            name='feature5',
        ),
        migrations.AddField(
            model_name='place',
            name='Reasons_to_visit',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
        migrations.AddField(
            model_name='place',
            name='features_to_mention',
            field=ckeditor.fields.RichTextField(default=' '),
        ),
    ]
