# Generated by Django 3.0.7 on 2021-05-09 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0027_auto_20210430_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='feature5',
            field=models.CharField(blank=True, default=' ', max_length=100),
        ),
    ]
