# Generated by Django 3.0.7 on 2021-05-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0028_auto_20210509_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='feature5',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
