# Generated by Django 3.0.7 on 2021-05-10 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0029_auto_20210509_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='no_of_visitors',
            field=models.CharField(default='Around x million', max_length=1000000),
        ),
    ]
