# Generated by Django 3.0.7 on 2021-05-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0030_auto_20210510_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='Max_temperature',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='Min_temperature',
            field=models.CharField(default='', max_length=100),
        ),
    ]
