# Generated by Django 3.0.7 on 2021-05-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0031_auto_20210510_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
