# Generated by Django 3.0.7 on 2021-05-10 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0032_place_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='is_trending',
        ),
    ]
